name: Cleanup Old Artifacts

on:
  schedule:
    # Run daily at 2 AM UTC to clean up old artifacts
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering of the cleanup

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            
            // Get all artifacts
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner,
              repo,
              per_page: 100
            });
            
            console.log(`Found ${artifacts.data.total_count} total artifacts`);
            
            // Keep artifacts from the last 7 days only
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - 7);
            
            let deletedCount = 0;
            
            for (const artifact of artifacts.data.artifacts) {
              const createdDate = new Date(artifact.created_at);
              
              if (createdDate < cutoffDate) {
                try {
                  await github.rest.actions.deleteArtifact({
                    owner,
                    repo,
                    artifact_id: artifact.id
                  });
                  console.log(`Deleted artifact: ${artifact.name} (created: ${artifact.created_at})`);
                  deletedCount++;
                } catch (error) {
                  console.log(`Failed to delete artifact ${artifact.id}: ${error.message}`);
                }
              }
            }
            
            console.log(`Deleted ${deletedCount} old artifacts`);
            
            if (deletedCount === 0) {
              console.log('No old artifacts found to delete');
            }